argocd-operator release 0.8.0
argoproj-labs/argocd-operator pull request #1020
Opened 2023-10-18 14:40 UTC by reginapizza

**What type of PR is this?**
> /kind chore

**What does this PR do / why we need it**:
Releases argocd-operator 0.8.0
+ also upgrades argocd version to 2.8.4

2023-10-19 14:56 UTC, iam-veeramalla requested changes
Looks good to me otherwise

2023-10-19 14:56 UTC, iam-veeramalla commented on bundle/metadata/annotations.yaml
> +  operators.operatorframework.io.metrics.builder: operator-sdk-v1.31.0
Please revert this change

2023-10-19 14:56 UTC, iam-veeramalla commented on deploy/olm-catalog/argocd-operator/0.8.0/argocd-operator.v0.8.0.clusterserviceversion.yaml
> +    operators.operatorframework.io/builder: operator-sdk-v1.31.0
Please revert this change.

2023-10-19 15:29 UTC, reginapizza commented
ah okay thanks, wasn't sure why that was happening- I think when I switched to my new laptop I just downloaded the latest operator-sdk without thinking about versioning with this. I'll update the PR!

2023-10-19 15:31 UTC, reginapizza commented
@iam-veeramalla should I use operator-sdk v.11.0  or v1.10 like it was before here?

2023-10-27 06:07 UTC, iam-veeramalla approved these changes
/lgtm

2023-10-31 19:14 UTC, jaideepr97 commented on build/util/Dockerfile
> +FROM quay.io/argoproj/argocd@sha256:f02d31d4b115d79de3dc45ebeec3a3107b9178d980e69d9dc2b26019d43f3e09 as argocd
please use v2.8.5 instead

2023-10-31 19:16 UTC, jaideepr97 commented
@reginapizza I would recommend creating an alias for your git commit command so that the signoff is automatically added

2023-10-31 19:35 UTC, jaideepr97 approved these changes
lgtm
thanks @reginapizza

2023-11-02 14:42 UTC, merged