rebase: update main.go, go mod files and docs (3/?)
argoproj-labs/argocd-operator pull request #1135
Opened 2024-01-05 18:57 UTC by jaideepr97

**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

> /kind bug
> /kind chore
> /kind cleanup
> /kind failing-test
> /kind enhancement
> /kind documentation
> /kind code-refactoring

**What does this PR do / why we need it**:
3/(?) PRs to rebase the redesgin branch

This PR does:
- update main.go 
- update go.mod and go.sum
- update docs folder 

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**How to test changes / Special notes to the reviewer**:

2024-01-05 21:20 UTC, ciiay requested changes
There are a few rebase issues left in the code. The rest looks good.

2024-01-05 21:20 UTC, ciiay commented on docs/install/manual.md
> +<<<<<<< HEAD
Some rebase issue.

2024-01-05 21:20 UTC, ciiay commented on docs/install/manual.md
> +>>>>>>> aa399a55abf577809d487fdc2811219cebb1cb35
Rebase issue.

2024-01-05 21:20 UTC, ciiay commented on docs/reference/argocd.md
> +<<<<<<< HEAD
Here too

2024-01-05 21:20 UTC, ciiay commented on docs/reference/argocd.md
> +>>>>>>> aa399a55abf577809d487fdc2811219cebb1cb35
Here

2024-01-05 21:20 UTC, ciiay commented on docs/reference/argocd.md
> +<<<<<<< HEAD
Here

2024-01-05 21:20 UTC, ciiay commented on docs/reference/argocd.md
> +>>>>>>> aa399a55abf577809d487fdc2811219cebb1cb35
Here

2024-01-08 17:36 UTC, ciiay approved these changes
LGTM
Thank you!

2024-01-09 11:18 UTC, svghadi approved these changes
/lgtm

2024-01-09 11:49 UTC, merged