Fix status operation value to allow less than 10
argoproj-labs/argocd-operator pull request #1198
Opened 2024-01-26 19:33 UTC by anandrkskd

**What type of PR is this?**
 /kind bug

**What does this PR do / why we need it**:
Currently, when we set application-controller 'status/operation processor' values below 10, it set it to default value of 10.
This PR allows the value to be less than the default value, but is the value is less or equals to 0 it sets it back to the default value.

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes [GITOPS-3770](https://issues.redhat.com/browse/GITOPS-3770)

**How to test changes / Special notes to the reviewer**:

2024-01-29 18:51 UTC, jaideepr97 approved these changes
LGTM thanks @anandrkskd

2024-01-29 18:53 UTC, jaideepr97 requested changes
please add a test case between 0 and the default

2024-02-01 07:15 UTC, svghadi approved these changes
LGTM. Thanks

2024-02-01 12:24 UTC, jaideepr97 approved these changes

2024-02-01 12:25 UTC, merged