Update ingressClassName of ingress based on ArgoCD ingressClassName
argoproj-labs/argocd-operator pull request #1395
Opened 2024-06-03 10:47 UTC by Rizwana777

**What type of PR is this?**
> Fix update issue in Ingress 

JIRA LINK - https://issues.redhat.com/browse/GITOPS-3412

2024-06-05 04:39 UTC, jgwest requested changes

2024-06-05 04:39 UTC, jgwest commented on controllers/argocd/ingress_test.go
> +	exaistingIngressClassName := "test-name"
`exaistingIngressClassName` -> `existingIngressClassName`

2024-06-10 05:11 UTC, svghadi approved these changes
LGTM. Thanks @Rizwana777

2024-06-13 11:49 UTC, jgwest approved these changes
LGTM too, thanks @Rizwana777!

2024-06-13 11:50 UTC, merged