feat: log k8s create/update/delete actions
argoproj-labs/argocd-operator pull request #1615
Opened 2024-12-03 18:45 UTC by jopit

**What type of PR is this?**

/kind enhancement

**What does this PR do / why we need it**:

Logs Create/Update/Deletion actions performed by Argo CD operator

2024-12-11 08:34 UTC, jgwest requested changes
Looks great, thanks @jopit! And thanks for going through all the code and adding all these statements, I appreciate it as it was likely both somewhat monotonous work :smile:, but also a case where its important to get the details right (and that combination can be deadly!)

I'm definitely looking forward to these changes making it into product code, as it should make working with user/customer operator logs much easier.

Everything looks great, just one suggestion around checking for `nil` on the logged object then good to go.

2024-12-11 20:05 UTC, jopit commented on controllers/argoutil/resource.go
> +	typeName := reflect.TypeOf(object).String()
Calling `log.Error(..)` already writes the stack trace to the log, so no need for the call to `debug.PrintStack()`

2024-12-11 20:52 UTC, jopit commented on controllers/argoutil/resource.go
> +	typeName := reflect.TypeOf(object).String()
Done.

2024-12-12 15:50 UTC, jgwest approved these changes
LGTM, thanks again @jopit!

2024-12-12 15:51 UTC, merged