Fix upgrade sync
argoproj-labs/argocd-operator pull request #1619
Opened 2024-12-12 09:28 UTC by Mangaal

**What type of PR is this?**
This PR fixes an issue where updates to the argocd-redis-ha-configmap, argocd-redis-ha-health-configmap, and the StatefulSet argocd-redis-ha-server were not being reflected during OpenShift GitOps operator upgrades.

The current code missed checking for changes in:
- The data field of argocd-redis-ha-configmap and argocd-redis-ha-health-configmap.
- The env variables in the StatefulSet argocd-redis-ha-server.

As a result, changes introduced in higher versions of the operator were not applied unless the config maps and  StatefulSet were manually deleted or the .spec.ha.enabled field was toggled in the ArgoCD Custom Resource (CR). This PR ensures these changes are correctly detected and applied.

This PR:
Adds logic to check for changes in the argocd-redis-ha-configmap and argocd-redis-ha-health-configmap data fields during operator upgrades.
Includes validation for the env variables in the argocd-redis-ha-server StatefulSet to ensure updates are reflected.
Ensures that any required updates are applied automatically without manual intervention.

 /kind bug 

Steps to reproduce the issue:

- Install OpenShift GitOps Operator v1.12.0 on an OCP 4.16.4 cluster.
- Create an ArgoCD instance with .spec.ha.enabled = true.
- Upgrade the operator to v1.14.0, v1.14.1, and v1.14.2.
- Observe that the argocd-redis-ha-configmap and argocd-redis-ha-health-configmap are not updated as expected.
- Delete the config maps manually, and observe that they are recreated correctly but result in AUTH errors.
- Toggle the .spec.ha.enabled field to fix the issue.

2024-12-24 07:25 UTC, svghadi commented
Can we add a unit test to check configmap reconciliation?

2025-01-03 05:36 UTC, svghadi approved these changes
Just a small nit, everything else looks great! Awesome job on the unit tests. Thanks!

2025-01-03 05:36 UTC, svghadi commented on controllers/argocd/configmap.go
> +			return r.Client.Delete(context.TODO(), existingCM)
```suggestion
                        argoutil.LogResourceDeletion(log, cm, "redis ha is disabled")
			return r.Client.Delete(context.TODO(), existingCM)
```
Can we log the deletion same as in the old code?

2025-01-03 05:36 UTC, svghadi commented on controllers/argocd/configmap.go
> +			return r.Client.Delete(context.TODO(), existingCM)
```suggestion
                        argoutil.LogResourceDeletion(log, cm, "redis ha is disabled")
			return r.Client.Delete(context.TODO(), existingCM)
```

2025-01-06 04:51 UTC, Mangaal commented on controllers/argocd/configmap.go
> +			return r.Client.Delete(context.TODO(), existingCM)
Thanks @svghadi , I have added the missing logs

2025-01-08 10:29 UTC, svghadi requested changes
Hi, Sorry nitpicking again. Your previous comments made sense in 2 places. Can you revert the changes for this. Also please rebase, I have just merged a PR which will fix failing extra-cmd e2e test.

2025-01-08 10:29 UTC, svghadi commented on controllers/argocd/configmap.go
> +		return nil // ConfigMap found with nothing changed, move along...
```suggestion
		return nil // Nothing to do since HA is not enabled and ConfigMap does not exist
```
Your older comment made sense here.

2025-01-08 10:29 UTC, svghadi commented on controllers/argocd/configmap.go
> +		return nil // ConfigMap found with nothing changed, move along...
```suggestion
		return nil // Nothing to do since HA is not enabled and ConfigMap does not exist
```

2025-01-09 11:35 UTC, svghadi commented
> --- FAIL: kuttl/harness/1-036_validate_role_rolebinding_for_source_namespace (64.05s)

is a known flaky failure. Ignoring it and merging the PR.

2025-01-09 11:35 UTC, svghadi approved these changes

2025-01-09 11:36 UTC, merged

2025-01-09 11:39 UTC, svghadi commented
/cherry-pick release-0.13