Bump Default ArgoCD and ApplicationSet versions
argoproj-labs/argocd-operator pull request #407
Opened 2021-08-25 18:42 UTC by tylerauerbeck

Signed-off-by: Tyler Auerbeck <tauerbec@redhat.com>

**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

> /kind bug
> /kind cleanup
> /kind failing-test
/kind enhancement
> /kind documentation
> /kind code-refactoring

**What does this PR do / why we need it**:

This bumps the default ArgoCD version to v2.1.0 and the default ApplicationSet version to v0.2.0.

**Have you updated the necessary documentation?**

* [X] Documentation update is required by this PR.
* [X] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #403 

**How to test changes / Special notes to the reviewer**:

Deploy an ArgoCD CR and verify that it deploys ArgoCD v2.1.0 and ApplicationSet v0.2.0

2021-08-31 05:53 UTC, iam-veeramalla commented
@tylerauerbeck Can you please rebase the PR ? We got the `operator-sdk upgrade` merged so all the PR's needs to be rebased.

2021-08-31 16:09 UTC, jannfis requested changes
Can we also bump to v2.1.1 instead of v2.1.0 please?

2021-09-02 20:32 UTC, iam-veeramalla commented
@tylerauerbeck Can you please take a look at this, let me know if you need any help on this :)

2021-09-03 07:34 UTC, jannfis commented
Oh, and [v2.1.2](https://github.com/argoproj/argo-cd/releases/tag/v2.1.2) has also just been released yesterday, which fixed a couple of bugs :)

2021-09-03 11:55 UTC, tylerauerbeck commented
No problem. Will get this updated today.

2021-09-03 13:28 UTC, tylerauerbeck commented
@jannfis @iam-veeramalla This should be in better shape and with the latest versions.

2021-09-03 19:48 UTC, jannfis approved these changes
LGTM, thank you @tylerauerbeck !

2021-09-03 19:48 UTC, merged