chore: update appset controller
argoproj-labs/argocd-operator pull request #579
Opened 2022-03-01 13:48 UTC by ishitasequeira

**What type of PR is this?**
kind chore

**What does this PR do / why we need it**: ApplicationSet is merged to ArgoCD repo ([GITOPS-1621](https://issues.redhat.com/browse/GITOPS-1621)). ArgoCD Operator needs to be updated accordingly

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**: ([GITOPS-1653](https://issues.redhat.com/browse/GITOPS-1653))

Fixes #?

**How to test changes / Special notes to the reviewer**:

Signed-off-by: ishitasequeira <isequeir@redhat.com>

2022-03-01 17:21 UTC, jaideepr97 commented
@ishitasequeira could you run `make bundle generate manifests` and push again?

2022-03-01 21:12 UTC, jaideepr97 commented on controllers/argocd/applicationset.go
> +			if err := r.Client.Delete(context.TODO(), existing); err != nil {
can we have a `log.Info` here that mentions that the applicationSet deployment is being deleted because applicationSet was disabled?

2022-03-01 21:13 UTC, jaideepr97 commented on controllers/argocd/applicationset.go
> +			if err := r.Client.Delete(context.TODO(), sa); err != nil {
can we have a `log.Info` here that mentions that the applicationSet service account is being deleted because applicationSet was disabled?

2022-03-01 21:13 UTC, jaideepr97 commented on controllers/argocd/applicationset.go
> +			if err := r.Client.Delete(context.TODO(), role); err != nil {
can we have a `log.Info` here that mentions that the applicationSet role is being deleted because applicationSet was disabled?

2022-03-01 21:13 UTC, jaideepr97 commented on controllers/argocd/applicationset.go
> +			if err := r.Client.Delete(context.TODO(), roleBinding); err != nil {
can we have a `log.Info` here that mentions that the applicationSet roleBinding is being deleted because applicationSet was disabled?

2022-03-01 22:56 UTC, wtam2018 commented
@ishitasequeira is "disabled" the only thing needed? I don't think we need to add this flag.

2022-03-02 02:23 UTC, wtam2018 commented
Instead of adding a disabled flag, I think we should pull in a v2.3 (rc) and install/run it to see what exactly need to be changed.  You are sill installing v2.2, right?

2022-03-04 13:39 UTC, jannfis reviewed
Just a nit. Otherwise, looks fine!

2022-03-04 13:39 UTC, jannfis commented on controllers/argocd/applicationset.go
>  	}
We probably should do that also only if ApplicationSet is not disabled. It just makes no sense to call `SetControllerReference` if we're not going to reconcile anyway.

2022-03-04 14:00 UTC, wtam2018 requested changes
Let's rethink if it makes sense to add "disabled" flag to applicationset. It does not provide really benefit to the users. It only makes the code more complicated and harder to maintain. None of the core servers (e.g. application controller, repo server) has disabled flag. Also, we are talking about tighter integration of applicationset to argocd controller upstream.

2022-03-04 23:07 UTC, closed without merging