Added reconcilation logic if spec.ApplicationSet is removed
argoproj-labs/argocd-operator pull request #670
Opened 2022-06-02 08:26 UTC by rishabh625

Signed-off-by: rishabh625 <rishabhmishra625@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

> /kind bug
> /kind chore
> /kind cleanup
> /kind failing-test
> /kind enhancement
> /kind documentation
> /kind code-refactoring

/kind bug

**What does this PR do / why we need it**:
This PR deletes application set resources if disabled.

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**How to test changes / Special notes to the reviewer**:

2022-06-03 07:11 UTC, iam-veeramalla commented on controllers/argocd/util.go
> +	// Add new predicate to delete Notifications Resources. The predicate watches the Argo CD CR for changes to the `.spec.Notifications.Enabled`
Please update the comments to modify Notifications as ApplicationSet. To be changed in multiple places, please take care

2022-06-03 07:14 UTC, iam-veeramalla commented on controllers/argocd/applicationset.go
> +//deleteApplicationSetResources ... Triggers reconcillation of application set resources,logic for deletion of applicationset is in reconcile methods this method triggers the cleanup of resources usi
If please fix the below in comments.

1. Provide space after // 
2. remove ...
3. typo in reconciliation

May be
// deleteApplicationSetResources triggers the cleanup of application set resources.

2022-06-03 07:16 UTC, iam-veeramalla commented on controllers/argocd/applicationset.go
> +			return r.Client.Delete(context.TODO(), existing)
When I removed the applicationSet entry from Argo CD CR, controller crashed with the below error. I edited the Argo CD CR to remove the `.spec.applicationSet` entry.

```
1.6542400631086211e+09	INFO	controller_argocd	reconciling ApplicationSet deployment
E0603 12:37:43.108966   18003 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 506 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x237e8a0?, 0x3477f10})
	/Users/aveerama/go/src/github.com/iam-veeramalla/argocd-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x86
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x8?})
	/Users/aveerama/go/src/github.com/iam-veeramalla/argocd-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x75
panic({0x237e8a0, 0x3477f10})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/argoproj-labs/argocd-operator/controllers/argocd.getArgoApplicationSetCommand(0xc000b80000)
	/Users/aveerama/go/src/github.com/iam-veeramalla/argocd-operator/controllers/argocd/applicationset.go:47 +0x285
github.com/argoproj-labs/argocd-operator/controllers/argocd.applicationSetContainer(_)
	/Users/aveerama/go/src/github.com/iam-veeramalla/argocd-operator/controllers/argocd/applicationset.go:190 +0x152
```

2022-06-03 07:20 UTC, iam-veeramalla requested changes
Operator Crashed when ApplicationSet entry is removed from CR. I followed below steps

Created the Argo CD CR using 
```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
  labels:
    example: ingress
spec:
  applicationSet: {}
  server:
    grpc:
      ingress:
        enabled: true
    ingress:
      enabled: true
    insecure: true
```

After a while(once all the resources are created), I removed the entry for ApplicationSet from CR using `oc edit`

Please add steps to reproduce or test the PR in the description section.

2022-06-03 07:24 UTC, rishabh625 commented
Sure will look at all Thanks @iam-veeramalla

2022-06-10 21:29 UTC, jaideepr97 commented on controllers/argocd/applicationset_test.go
> +}
are these resources actually getting created in the first place? I don't see a call to reconcile these resources
I think we should make sure to first check that the resources exist and before setting `a.spec.applicationset` to nil in order to be sure the test is accurate and that resources are in fact being deleted as expected

2022-06-10 21:44 UTC, jaideepr97 commented
@rishabh625 
I think the nil pointer reference @iam-veeramalla mentioned is coming from here https://github.com/argoproj-labs/argocd-operator/pull/670/files#diff-547555dfe97d80ddf6097444f1cc82263cce61c48fbb67f6bb8e08c657873bc6L46
we should check if `cr.spec.applicationset != nil` first

2022-06-14 19:36 UTC, rishabh625 commented
> @rishabh625 I think the nil pointer reference @iam-veeramalla mentioned is coming from here https://github.com/argoproj-labs/argocd-operator/pull/670/files#diff-547555dfe97d80ddf6097444f1cc82263cce61c48fbb67f6bb8e08c657873bc6L46 we should check if `cr.spec.applicationset != nil` first

thanks @jaideepr97 will look into this, was waiting  for discussion

2022-08-17 12:51 UTC, jaideepr97 commented on .github/workflows/test.yaml
> +      run: echo Hello, world!
is this file meant to be here?

2022-08-17 12:52 UTC, jaideepr97 commented on api/v1alpha1/argocd_types.go
> +	//+operator-sdk:csv:customresourcedefinitions:type=status,displayName="ApplicationController",xDescriptors={"urn:alm:descriptor:com.tectonic.ui:text"}
ApplicationController ==> ApplicationSetController

2022-08-17 12:53 UTC, jaideepr97 commented on controllers/argocd/applicationset.go
> +<<<<<<< HEAD
@rishabh625 looks like something went wrong while resolving merge conflicts

2022-08-17 17:46 UTC, rishabh625 commented on controllers/argocd/applicationset.go
> +<<<<<<< HEAD
yeah fixed

2026-03-15 09:56 UTC, olivergondza commented
Thanks for filing this PR. Please resolve the merge conflict or indicate that you are no longer interested to contribute this patch.

2026-06-15 12:33 UTC, olivergondza commented
This was implemented by https://github.com/argoproj-labs/argocd-operator/pull/2134.

2026-06-15 12:33 UTC, closed without merging