bug: appset status not reflected in CR
argoproj-labs/argocd-operator pull request #829
Opened 2022-12-14 20:10 UTC by jaideepr97

Signed-off-by: Jaideep Rao <jaideep.r97@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

 /kind bug
> /kind chore
> /kind cleanup
> /kind failing-test
> /kind enhancement
> /kind documentation
> /kind code-refactoring

**What does this PR do / why we need it**:
This PR adds applicationSetController to `.status` of the Argo CD CR. This allows us to track the status/health of the appset controller workload in the CR, and lets us know if the controller is running as expected or pending if a pod couldn't come up. This is needed since it is a dependency for being able to set up monitoring alerts for all argo-cd workloads to be notified when they remain unavailable for too long

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes https://github.com/argoproj-labs/argocd-operator/issues/627

**How to test changes / Special notes to the reviewer**:

1. Start operator locally
2. Create basic Argo CD instance 
```
cat <<EOF | oc apply -f -
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
spec: {}
EOF

```

3. Verify that `.status.applicationSetController` is initially set to `Unknown`
```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
status:
  ...
  applicationSetController: Unknown
```

4. Enable applicationSet:
```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
spec:
  applicationSet: {}
```

5. Verify that `.status.applicationSetController` is initially set to `Running`
```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
status:
  ...
  applicationSetController: Running
```

6. Set `.spec.applicationSet.image` to some invalid image and delete existing appset deployment 
```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
spec:
  applicationSet:
    image: quay.io/argoproj/argocd@sha256:8283a9f06033c2377dc61b03daf49
```

7.  Verify that `.status.applicationSetController` is now set to `Pending` as the new controller pod fails to come up due to invalid image name
```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
status:
  ...
  applicationSetController: Pending
```

2022-12-19 04:04 UTC, ishitasequeira commented on api/v1alpha1/argocd_types.go
> +	// There are five possible ApplicationSetController values:
nit: `four possible ApplicationSetController values`

2022-12-19 04:04 UTC, ishitasequeira commented on api/v1alpha1/argocd_types.go
> +	// Unknown: For some reason the state of the Argo CD applicationSet controller component could not be obtained.
nit: remove `For some reason`

2022-12-19 04:43 UTC, ishitasequeira approved these changes
Except for few nits! PR LGTM!!

2022-12-19 13:14 UTC, jaideepr97 commented on api/v1alpha1/argocd_types.go
> +	// Unknown: For some reason the state of the Argo CD applicationSet controller component could not be obtained.
fixed in all comments, thanks

2022-12-22 16:05 UTC, iam-veeramalla commented on deploy/olm-catalog/argocd-operator/0.5.0/argoproj.io_argocds.yaml
> +  storedVersions: []
Update to 0.5.0 should be removed

2022-12-22 16:06 UTC, iam-veeramalla requested changes

2022-12-22 16:06 UTC, iam-veeramalla commented on deploy/olm-catalog/argocd-operator/0.5.0/argoproj.io_argocds.yaml
> +  storedVersions: []
Updates to 0.5.0 should be removed

2022-12-22 16:06 UTC, iam-veeramalla commented on deploy/olm-catalog/argocd-operator/0.5.0/argocd-operator.v0.5.0.clusterserviceversion.yaml
> +  version: 0.5.0
Updates to 0.5.0 should be removed

2022-12-22 16:13 UTC, jaideepr97 commented on deploy/olm-catalog/argocd-operator/0.5.0/argoproj.io_argocds.yaml
> +  storedVersions: []
done

2022-12-22 16:13 UTC, jaideepr97 commented on deploy/olm-catalog/argocd-operator/0.5.0/argocd-operator.v0.5.0.clusterserviceversion.yaml
> +  version: 0.5.0
done

2022-12-22 16:14 UTC, iam-veeramalla approved these changes

2022-12-22 17:52 UTC, merged